const wilayas=["أدرار","الشلف","الأغواط","أم البواقي","باتنة","بجاية","بسكرة","بشار","البليدة","البويرة","تمنراست","تبسة","تلمسان","تيارت","تيزي وزو","الجزائر","الجلفة","جيجل","سطيف","سعيدة","سكيكدة","سيدي بلعباس","عنابة","قالمة","قسنطينة","المدية","مستغانم","المسيلة","معسكر","ورقلة","وهران","البيض","إليزي","برج بوعريريج","بومرداس","الطارف","تندوف","تيسمسيلت","الوادي","خنشلة","سوق أهراس","تيبازة","ميلة","عين الدفلى","النعامة","عين تموشنت","غرداية","غليزان","تيميمون","برج باجي مختار","أولاد جلال","بني عباس","عين صالح","عين قزام","تقرت","جانت","المغير","المنيعة"];
const $=s=>document.querySelector(s), state={user:null,messages:[]};
$("#wilaya").innerHTML='<option value="">اختر ولايتك</option>'+wilayas.map(x=>`<option>${x}</option>`).join("");
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");const reg=b.dataset.tab==="register";$("#registerForm").hidden=!reg;$("#loginForm").hidden=reg;$("#authMsg").textContent=""});
function compressProfilePhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const size=320,canvas=document.createElement("canvas"),scale=Math.min(size/img.width,size/img.height,1);canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.78))};img.onerror=()=>reject(new Error("bad-image"));img.src=reader.result};reader.onerror=()=>reject(new Error("read-error"));reader.readAsDataURL(file)})}
const photoInput=$("#profilePhoto"),photoPreview=$("#profilePreview");
photoInput?.addEventListener("change",()=>{const f=photoInput.files[0];if(!f)return;if(f.size>5*1024*1024){photoInput.value="";photoPreview.hidden=true;$("#authMsg").textContent="حجم الصورة لازم يكون أقل من 5 ميغابايت.";return}photoPreview.src=URL.createObjectURL(f);photoPreview.hidden=false;$("#authMsg").textContent=""});
function load(){const u=localStorage.getItem("nourUser");if(u){state.user=JSON.parse(u);showChat()}}
function showChat(){$("#authView").hidden=true;$("#chatView").hidden=false;$("#me").textContent=`@${state.user.username} · ${state.user.wilaya}`;renderUsers();renderMessages()}
function renderUsers(){$("#users").innerHTML=["أمين","سارة","محمد","ليلى"].filter(x=>x!==state.user.username).map(x=>`<div class="user">● ${x}</div>`).join("")}
function renderMessages(){const el=$("#messages");el.innerHTML=state.messages.map(m=>`<div class="bubble ${m.u===state.user.username?"mine":""}"><b>${escapeHtml(m.u)}</b>${escapeHtml(m.t)}</div>`).join("");el.scrollTop=el.scrollHeight}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
$("#registerForm").onsubmit=async e=>{e.preventDefault();const p=$("#password").value;const photo=photoInput?.files?.[0];if(!photo)return $("#authMsg").textContent="لازم تختار صورة بروفايل لإكمال إنشاء الحساب.";if(p!==$("#confirmPassword").value)return $("#authMsg").textContent="كلمتا المرور غير متطابقتين.";if(Number($("#age").value)<18)return $("#authMsg").textContent="الموقع مخصص لمن أعمارهم 18 سنة أو أكثر.";try{state.user={username:$("#username").value.trim(),age:Number($("#age").value),wilaya:$("#wilaya").value,profilePhoto:await compressProfilePhoto(photo)};localStorage.setItem("nourUser",JSON.stringify(state.user));showChat()}catch(err){$("#authMsg").textContent="تعذر حفظ صورة البروفايل، جرّب صورة أخرى."}};
$("#loginForm").onsubmit=e=>{e.preventDefault();const u=$("#loginUsername").value.trim();if(!u)return;state.user={username:u,wilaya:"الجزائر"};localStorage.setItem("nourUser",JSON.stringify(state.user));showChat()};
$("#messageForm").onsubmit=e=>{e.preventDefault();const t=$("#message").value.trim();if(!t)return;state.messages.push({u:state.user.username,t});$("#message").value="";renderMessages()};
$("#logout").onclick=()=>{localStorage.removeItem("nourUser");location.reload()};load();