const SUPABASE_URL="https://fiqqkexapeivhvoigomv.supabase.co";
const SUPABASE_KEY="sb_publishable__K-3VfJgl21taaQVfgiXNA_o0AdTHU7";
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const wilayas=["أدرار","الشلف","الأغواط","أم البواقي","باتنة","بجاية","بسكرة","بشار","البليدة","البويرة","تمنراست","تبسة","تلمسان","تيارت","تيزي وزو","الجزائر","الجلفة","جيجل","سطيف","سعيدة","سكيكدة","سيدي بلعباس","عنابة","قالمة","قسنطينة","المدية","مستغانم","المسيلة","معسكر","ورقلة","وهران","البيض","إليزي","برج بوعريريج","بومرداس","الطارف","تندوف","تيسمسيلت","الوادي","خنشلة","سوق أهراس","تيبازة","ميلة","عين الدفلى","النعامة","عين تموشنت","غرداية","غليزان","تيميمون","برج باجي مختار","أولاد جلال","بني عباس","عين صالح","عين قزام","تقرت","جانت","المغير","المنيعة"];
const $=s=>document.querySelector(s);
const state={user:null,profile:null,selectedUser:null,messages:[],profiles:[],channel:null,notificationChannel:null,unread:{}};
$("#wilaya").innerHTML='<option value="">اختر ولايتك</option>'+wilayas.map(x=>'<option>'+x+'</option>').join("");
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");const reg=b.dataset.tab==="register";$("#registerForm").hidden=!reg;$("#loginForm").hidden=reg;$("#authMsg").textContent=""});
function msg(t){$("#authMsg").textContent=t||""}
function internalEmail(username){const bytes=new TextEncoder().encode(username.trim().toLowerCase());return Array.from(bytes).map(b=>b.toString(16).padStart(2,"0")).join("")+"@nour-el7alal.com"}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function compressImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const size=600,c=document.createElement("canvas"),scale=Math.min(size/img.width,size/img.height,1);c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext("2d").drawImage(img,0,0,c.width,c.height);c.toBlob(b=>b?resolve(b):reject(new Error("image")),"image/jpeg",.82)};img.onerror=()=>reject(new Error("image"));img.src=r.result};r.onerror=()=>reject(new Error("file"));r.readAsDataURL(file)})}
const photoInput=$("#profilePhoto"),photoPreview=$("#profilePreview");
photoInput?.addEventListener("change",()=>{const f=photoInput.files[0];if(!f)return;if(f.size>5*1024*1024){photoInput.value="";photoPreview.hidden=true;msg("حجم الصورة لازم يكون أقل من 5 ميغابايت.");return}photoPreview.src=URL.createObjectURL(f);photoPreview.hidden=false;msg("")});
async function uploadAvatar(userId,file){const blob=await compressImage(file);const path=userId+"/avatar.jpg";const {error}=await supabaseClient.storage.from("avatars").upload(path,blob,{contentType:"image/jpeg",upsert:true});if(error)throw error;const {data}=supabaseClient.storage.from("avatars").getPublicUrl(path);return {path,url:data.publicUrl}}
async function loadProfile(userId){const {data,error}=await supabaseClient.from("profiles").select("*").eq("id",userId).single();if(error)throw error;state.profile=data;state.user={id:userId,...data}}
async function showChat(){if(!state.profile)return;$("#authView").hidden=true;$("#chatView").hidden=false;$("#siteBanner").hidden=true;startNotifications();$("#me").textContent="@"+state.profile.username+" · "+(state.profile.wilaya||"");$("#myAvatar").innerHTML=state.profile.avatar_url?'<img src="'+escapeHtml(state.profile.avatar_url)+'" alt="">':escapeHtml((state.profile.username||"ن")[0]);$("#message").disabled=true;$(".send-btn").disabled=true;await loadProfiles();initChatUX()}
async function loadProfiles(){const {data,error}=await supabaseClient.from("profiles").select("id,username,full_name,wilaya,age,avatar_url,avatar_path").order("updated_at",{ascending:false});if(error){console.error(error);return}state.profiles=(data||[]).filter(p=>p.id!==state.user.id);renderUsers()}
function renderUsers(){const q=($("#userSearch")?.value||"").trim().toLowerCase();const people=state.profiles.filter(p=>!q||p.username.toLowerCase().includes(q)||(p.wilaya||"").toLowerCase().includes(q));$("#users").innerHTML=people.map(p=>{const selected=state.selectedUser?.id===p.id;const av=p.avatar_url?'<img src="'+escapeHtml(p.avatar_url)+'" alt="">':escapeHtml((p.username||"ن")[0]);return '<button class="user '+(selected?"selected":"")+'" data-id="'+escapeHtml(p.id)+'"><span class="avatar-sm">'+av+'</span><span><b>'+escapeHtml(p.username)+'</b><small>'+escapeHtml(p.wilaya||"الجزائر")+'</small></span><i>●</i>'+(state.unread[p.id]?'<em class="unread-badge">'+state.unread[p.id]+'</em>':"")+'</button>'}).join("");$("#onlineCount").textContent=people.length;document.querySelectorAll(".user").forEach(e=>e.onclick=()=>selectUser(e.dataset.id))}
async function selectUser(id){const p=state.profiles.find(x=>x.id===id);if(!p)return;state.unread[id]=0;state.selectedUser=p;$("#roomName").textContent=p.username;$("#roomStatus").textContent=(p.wilaya||"الجزائر")+" • محادثة خاصة";$(".active-avatar").innerHTML=p.avatar_url?'<img src="'+escapeHtml(p.avatar_url)+'" alt="">':escapeHtml((p.username||"ن")[0]);$("#message").disabled=false;$(".send-btn").disabled=false;$("#message").placeholder="اكتب رسالة محترمة...";renderUsers();await loadMessages()}
async function loadMessages(){if(!state.selectedUser)return;const me=state.user.id,other=state.selectedUser.id;const {data,error}=await supabaseClient.from("messages").select("id,sender_id,recipient_id,body,created_at,edited_at,deleted_at").or("and(sender_id.eq."+me+",recipient_id.eq."+other+"),and(sender_id.eq."+other+",recipient_id.eq."+me+")").order("created_at",{ascending:true});if(error){console.error(error);return}state.messages=data||[];renderMessages();subscribeMessages()}
function renderMessages(){const el=$("#messages");if(!state.selectedUser){el.innerHTML='<div class="welcome-chat"><div class="welcome-icon">💬</div><h3>مرحبا بك في نور الحلال</h3><p>اختر عضوًا من القائمة لبدء محادثة خاصة.</p></div>';return}if(!state.messages.length){el.innerHTML='<div class="welcome-chat"><div class="welcome-icon">💬</div><h3>ابدأ المحادثة</h3><p>أرسل أول رسالة محترمة إلى '+escapeHtml(state.selectedUser.username)+'.</p></div>';return}el.innerHTML=state.messages.map(m=>'<div class="bubble '+(m.sender_id===state.user.id?"mine":"")+'"><b>'+escapeHtml(m.sender_id===state.user.id?state.profile.username:state.selectedUser.username)+'</b><span>'+escapeHtml(m.deleted_at?"تم حذف الرسالة":m.body)+'</span><time>'+new Date(m.created_at).toLocaleTimeString("ar-DZ",{hour:"2-digit",minute:"2-digit"})+'</time></div>').join("");el.scrollTop=el.scrollHeight}
function subscribeMessages(){if(state.channel)supabaseClient.removeChannel(state.channel);if(!state.selectedUser)return;const other=state.selectedUser.id;state.channel=supabaseClient.channel("private-chat-"+state.user.id+"-"+other).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:"recipient_id=eq."+state.user.id},payload=>{if(payload.new.sender_id===other){state.messages.push(payload.new);renderMessages()}}).subscribe()}
function notifyMessage(message){const sender=state.profiles.find(p=>p.id===message.sender_id);const name=sender?.username||"عضو جديد";const text=String(message.body||"رسالة جديدة").slice(0,120);if(document.hidden&&"Notification" in window&&Notification.permission==="granted"){new Notification("نور الحلال • "+name,{body:text,icon:sender?.avatar_url||undefined,tag:"message-"+message.id})}if(navigator.vibrate)navigator.vibrate([120,60,120])}
function startNotifications(){if(state.notificationChannel)return;state.notificationChannel=supabaseClient.channel("all-messages-"+state.user.id).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:"recipient_id=eq."+state.user.id},payload=>{const m=payload.new;if(m.sender_id===state.user.id)return;if(state.selectedUser?.id===m.sender_id){state.messages.push(m);renderMessages();return}state.unread[m.sender_id]=(state.unread[m.sender_id]||0)+1;renderUsers();notifyMessage(m)}).subscribe();if("Notification" in window&&Notification.permission==="default"){setTimeout(()=>Notification.requestPermission().catch(()=>{}),1500)}}
async function register(e){e.preventDefault();const username=$("#username").value.trim(),password=$("#password").value,age=Number($("#age").value),wilaya=$("#wilaya").value,photo=photoInput?.files?.[0];if(!photo)return msg("لازم تختار صورة بروفايل.");if(password!==$("#confirmPassword").value)return msg("كلمتا المرور غير متطابقتين.");if(age<18)return msg("الموقع مخصص لمن أعمارهم 18 سنة أو أكثر.");if(!wilaya)return msg("اختر الولاية.");if(!/^[\p{L}\p{N}_ .-]{3,30}$/u.test(username))return msg("اسم المستخدم يجب أن يكون بين 3 و30 حرفًا.");msg("جاري إنشاء الحساب...");try{const {data,error}=await supabaseClient.functions.invoke("create-nour-account",{body:{username,password,age,wilaya}});if(error)throw error;if(!data?.ok)throw new Error(data?.error==="username_taken"?"اسم المستخدم مستعمل من قبل.":data?.details||data?.error||"تعذر إنشاء الحساب.");const {data:loginData,error:loginError}=await supabaseClient.auth.signInWithPassword({email:internalEmail(username),password});if(loginError)throw loginError;await loadProfile(loginData.user.id);const avatar=await uploadAvatar(loginData.user.id,photo);const {error:updateError}=await supabaseClient.from("profiles").update({avatar_path:avatar.path,avatar_url:avatar.url}).eq("id",data.user_id);if(updateError)throw updateError;state.profile.avatar_path=avatar.path;state.profile.avatar_url=avatar.url;await showChat()}catch(err){console.error(err);msg(err.message||"تعذر إنشاء الحساب.")}}
async function login(e){e.preventDefault();msg("جاري تسجيل الدخول...");try{const username=$("#loginUsername").value.trim();if(!username)return msg("اكتب اسم المستخدم.");const {data,error}=await supabaseClient.auth.signInWithPassword({email:internalEmail(username),password:$("#loginPassword").value});if(error)throw error;await loadProfile(data.user.id);await showChat()}catch(err){console.error(err);msg(err.message||"تعذر تسجيل الدخول.")}}
async function sendMessage(e){e.preventDefault();if(!state.selectedUser)return msg("اختر عضوًا أولًا.");const body=$("#message").value.trim();if(!body)return;const {data,error}=await supabaseClient.from("messages").insert({sender_id:state.user.id,recipient_id:state.selectedUser.id,body}).select("id,sender_id,recipient_id,body,created_at,edited_at,deleted_at").single();if(error){console.error(error);alert(error.message);return}state.messages.push(data);$("#message").value="";renderMessages()}
async function showSection(section){
 const panel=$("#communityPanel"); panel.hidden=false;
 if(section==="profile"){panel.innerHTML='<div class="panel-head"><h3>حسابي</h3><button id="closePanel">×</button></div><div class="profile-card-large"><div class="big-avatar">'+(state.profile.avatar_url?'<img src="'+escapeHtml(state.profile.avatar_url)+'" alt="">':escapeHtml((state.profile.username||"ن")[0]))+'</div><h3>'+escapeHtml(state.profile.username)+'</h3><p>'+escapeHtml(state.profile.age||"")+" سنة • "+escapeHtml(state.profile.wilaya||"الجزائر")+'</p><textarea id="bioEdit" placeholder="اكتب نبذة عنك...">'+escapeHtml(state.profile.bio||"")+'</textarea><div class="profile-grid"><input id="professionEdit" placeholder="المهنة" value="'+escapeHtml(state.profile.profession||"")+'"><input id="educationEdit" placeholder="المستوى الدراسي" value="'+escapeHtml(state.profile.education||"")+'"><select id="statusEdit"><option value="">الحالة الاجتماعية</option><option>أعزب/عزباء</option><option>مطلق/مطلقة</option><option>أرمل/أرملة</option></select><input id="seekingEdit" placeholder="أبحث عن..." value="'+escapeHtml(state.profile.seeking||"")+'"></div><button class="primary" id="saveProfile">حفظ الملف</button></div>';$("#closePanel").onclick=()=>panel.hidden=true;$("#saveProfile").onclick=async()=>{const update={bio:$("#bioEdit").value,profession:$("#professionEdit").value,education:$("#educationEdit").value,marital_status:$("#statusEdit").value||null,seeking:$("#seekingEdit").value};const {error}=await supabaseClient.from("profiles").update(update).eq("id",state.user.id);if(error)return alert(error.message);Object.assign(state.profile,update);alert("تم حفظ الملف.");};return}
 if(section==="discover"){panel.innerHTML='<div class="panel-head"><h3>البحث عن عضو</h3><button id="closePanel">×</button></div><div class="filter-grid"><input id="filterQ" placeholder="اسم المستخدم..."><select id="filterWilaya"><option value="">كل الولايات</option>'+wilayas.map(w=>'<option>'+escapeHtml(w)+'</option>').join("")+'</select><input id="filterMin" type="number" min="18" max="100" placeholder="العمر من"><input id="filterMax" type="number" min="18" max="100" placeholder="العمر إلى"></div><div id="discoverResults" class="discover-grid"></div>';$("#closePanel").onclick=()=>panel.hidden=true;const run=()=>{const q=($("#filterQ").value||"").toLowerCase(),w=$("#filterWilaya").value,min=Number($("#filterMin").value)||0,max=Number($("#filterMax").value)||100;const list=state.profiles.filter(p=>(!q||p.username.toLowerCase().includes(q))&&(!w||p.wilaya===w)&&(!p.age||p.age>=min&&p.age<=max));$("#discoverResults").innerHTML=list.map(p=>'<article class="discover-card"><div class="discover-avatar">'+(p.avatar_url?'<img src="'+escapeHtml(p.avatar_url)+'" alt="">':escapeHtml((p.username||"ن")[0]))+'</div><b>'+escapeHtml(p.username)+'</b><small>'+escapeHtml((p.age||"")+" سنة • "+(p.wilaya||"الجزائر"))+'</small><div><button class="mini-action like-btn" data-id="'+p.id+'">❤️ إعجاب</button><button class="mini-action request-btn" data-id="'+p.id+'">💍 طلب تعارف</button></div></article>').join("");document.querySelectorAll(".like-btn").forEach(b=>b.onclick=()=>likeProfile(b.dataset.id));document.querySelectorAll(".request-btn").forEach(b=>b.onclick=()=>sendRequest(b.dataset.id));};["filterQ","filterWilaya","filterMin","filterMax"].forEach(id=>$("#"+id).oninput=run);run();return}
 if(section==="requests"){const {data,error}=await supabaseClient.from("marriage_requests").select("id,sender_id,recipient_id,status,created_at").or("sender_id.eq."+state.user.id+",recipient_id.eq."+state.user.id).order("created_at",{ascending:false});if(error)return panel.innerHTML='<p>'+escapeHtml(error.message)+'</p>';const ids=[...new Set((data||[]).map(x=>x.sender_id===state.user.id?x.recipient_id:x.sender_id))];const people=state.profiles.filter(p=>ids.includes(p.id));panel.innerHTML='<div class="panel-head"><h3>طلبات التعارف</h3><button id="closePanel">×</button></div>'+(data||[]).map(r=>{const p=people.find(x=>x.id===(r.sender_id===state.user.id?r.recipient_id:r.sender_id));return '<div class="request-row"><span>'+escapeHtml(p?.username||"عضو")+'</span><b>'+escapeHtml(r.status)+'</b>'+(r.recipient_id===state.user.id&&r.status==="pending"?'<button class="mini-action accept-btn" data-id="'+r.id+'">قبول</button><button class="mini-action reject-btn" data-id="'+r.id+'">رفض</button>':"")+'</div>'}).join("");$("#closePanel").onclick=()=>panel.hidden=true;document.querySelectorAll(".accept-btn").forEach(b=>b.onclick=()=>updateRequest(b.dataset.id,"accepted"));document.querySelectorAll(".reject-btn").forEach(b=>b.onclick=()=>updateRequest(b.dataset.id,"rejected"));return}
 if(section==="offers"){const {data,error}=await supabaseClient.from("marriage_offers").select("id,owner_id,name,age,wilaya,gender,offer_type,bio,avatar_emoji,verified,online").eq("status","active").order("created_at",{ascending:false}).limit(30);if(error)return panel.innerHTML='<p>'+escapeHtml(error.message)+'</p>';panel.innerHTML='<div class="panel-head"><h3>عروض الزواج 💍</h3><button id="closePanel">×</button></div><div class="discover-grid">'+(data||[]).map(o=>'<article class="discover-card"><div class="discover-avatar">'+escapeHtml(o.avatar_emoji||"💍")+'</div><b>'+escapeHtml(o.name||"عضو")+'</b><small>'+escapeHtml((o.age||"")+" سنة • "+(o.wilaya||"الجزائر"))+'</small><p>'+escapeHtml(o.bio||"عرض زواج جاد")+'</p><button class="mini-action offer-request" data-id="'+o.owner_id+'">💍 تواصل</button></article>').join("")+'</div>';$("#closePanel").onclick=()=>panel.hidden=true;document.querySelectorAll(".offer-request").forEach(b=>b.onclick=()=>sendRequest(b.dataset.id));}
}
async function likeProfile(id){const {error}=await supabaseClient.from("profile_likes").upsert({user_id:state.user.id,target_id:id},{onConflict:"user_id,target_id"});if(error)alert(error.message);else alert("تم تسجيل الإعجاب ❤️")}
async function sendRequest(id){if(id===state.user.id)return;const {error}=await supabaseClient.from("marriage_requests").upsert({sender_id:state.user.id,recipient_id:id,status:"pending"},{onConflict:"sender_id,recipient_id"});if(error)alert(error.message);else alert("تم إرسال طلب التعارف 💍")}
async function updateRequest(id,status){const {error}=await supabaseClient.from("marriage_requests").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)alert(error.message);else showSection("requests")}
function initChatUX(){if(window.chatUX)return;window.chatUX=true;document.querySelectorAll(".community-nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".community-nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");showSection(b.dataset.section)});$("#searchToggle").onclick=()=>$("#searchBox").hidden=!$("#searchBox").hidden;$("#userSearch").oninput=renderUsers;$("#newChat").onclick=()=>{$("#searchBox").hidden=false;$("#userSearch").focus()};$("#roomMore").onclick=()=>{if(!state.selectedUser)return;alert("يمكن إضافة الحظر والإبلاغ بعد ربط جداول الإشراف.");};document.querySelectorAll(".quick-replies button").forEach(b=>b.onclick=()=>{if(!state.selectedUser)return;$("#message").value=b.textContent;$("#message").focus()});$("#emojiBtn").onclick=()=>{if(!state.selectedUser)return;$("#message").value+=" 😊";$("#message").focus()};$("#messageForm").onsubmit=sendMessage;$("#logout").onclick=async()=>{await supabaseClient.auth.signOut();if(state.channel)await supabaseClient.removeChannel(state.channel);if(state.notificationChannel)await supabaseClient.removeChannel(state.notificationChannel);location.reload()}}
async function boot(){const {data}=await supabaseClient.auth.getSession();if(data.session){try{await loadProfile(data.session.user.id);await showChat()}catch(err){console.error(err);await supabaseClient.auth.signOut()}}supabaseClient.auth.onAuthStateChange(async(event,session)=>{if(session&&!state.profile){try{await loadProfile(session.user.id);await showChat()}catch(err){console.error(err)}}})}
$("#registerForm").onsubmit=register;
$("#loginForm").onsubmit=login;
boot();